apiVersion: v1
kind: Service
metadata:
  name: result-db
  namespace: databases
spec:
  selector:
    app: result-db
  ports:
  - port: 1433
    targetPort: 1433
    name: mssql
  clusterIP: None
  type: ClusterIP
