apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: result-db
  namespace: databases
spec:
  serviceName: "result-db"
  replicas: 1
  selector:
    matchLabels:
      app: result-db
  template:
    metadata:
      labels:
        app: result-db
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
          name: mssql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: result-db-secret
              key: SA_PASSWORD
        - name: MSSQL_PID
          value: "Express"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
