apiVersion: v1
kind: Secret
metadata:
  name: result-service-secrets
  namespace: quizhub
type: Opaque
stringData:
  jwt-key: "SuperSecretKeyForJwtGenerationVerySecret"
  db-connection: "Server=result-db.databases.svc.cluster.local,1433;Database=ResultDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Connection Timeout=60;ConnectRetryCount=3;ConnectRetryInterval=10;"
