apiVersion: v1
kind: Secret
metadata:
  name: quiz-service-secrets
  namespace: quizhub
type: Opaque
stringData:
  jwt-key: "SuperSecretKeyForJwtGenerationVerySecret"
  db-connection: "Server=quiz-db.databases.svc.cluster.local,1433;Database=QuizDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;"
