apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: quizhub
type: Opaque
stringData:
  jwt-key: "SuperSecretKeyForJwtGenerationVerySecret"
  db-connection: "Server=user-db.databases.svc.cluster.local,1433;Database=UserDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;"
